import React from "react";

const page = () => {
  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-10">
      <h1 className="font-bold text-3xl sm:text-4xl text-start">
        Privacy Policy
      </h1>
      <p className="mt-3 text-sm sm:text-base text-gray-500">
        Last updated: <strong>November 6, 2025</strong>
      </p>
      <p className="mt-5 text-base sm:text-lg text-gray-500 leading-relaxed">
        This Privacy Policy describes Our policies and procedures on the
        collection, use and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the Privacy Policy Generator.
      </p>
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">
        Interpretation and Definitions
      </h2>
      <h3 className="font-bold text-xl sm:text-2xl mt-6">Interpretation</h3>
      <p className="mt-3 text-base sm:text-lg text-gray-500 leading-relaxed">
        The words whose initial letters are capitalized have meanings defined
        under the following conditions. The following definitions shall have the
        same meaning regardless of whether they appear in singular or in plural.
      </p>
      <h3 className="font-bold text-xl sm:text-2xl mt-6">Definitions</h3>
      <p className="mt-3 text-base sm:text-lg text-gray-500">
        For the purposes of this Privacy Policy:
      </p>
      <ul className="mt-4 space-y-3 text-base sm:text-lg text-gray-500 leading-relaxed">
        <li>
          <strong className="text-black">Account</strong> means a unique account
          created for You to access our Service or parts of our Service.
        </li>

        <li>
          <strong className="text-black">Affiliate</strong> means an entity that
          controls, is controlled by, or is under common control with a party,
          where "control" means ownership of 50% or more of the shares, equity
          interest or other securities entitled to vote for election of
          directors or other managing authority.
        </li>

        <li>
          <strong className="text-black">Company</strong> (referred to as either
          "the Company", "We", "Us" or "Our" in this Agreement) refers to unit
          converters.
        </li>

        <li>
          <strong className="text-black">Cookies</strong> are small files that
          are placed on Your computer, mobile device or any other device by a
          website, containing the details of Your browsing history on that
          website among its many uses.
        </li>

        <li>
          <strong className="text-black">Country</strong> refers to: Pakistan.
        </li>

        <li>
          <strong className="text-black">Device</strong> means any device that
          can access the Service such as a computer, a cell phone or a digital
          tablet.
        </li>

        <li>
          <strong className="text-black">Personal Data</strong> is any
          information that relates to an identified or identifiable individual.
        </li>

        <li>
          <strong className="text-black">Service</strong> refers to the Website.
        </li>

        <li>
          <strong className="text-black">Service Provider</strong> means any
          natural or legal person who processes the data on behalf of the
          Company. It refers to third-party companies or individuals employed by
          the Company to facilitate the Service, to provide the Service on
          behalf of the Company, to perform services related to the Service or
          to assist the Company in analyzing how the Service is used.
        </li>

        <li>
          <strong className="text-black">Usage Data</strong> refers to data
          collected automatically, either generated by the use of the Service or
          from the Service infrastructure itself.
        </li>

        <li>
          <strong className="text-black">Website</strong> refers to unit
          converters, accessible from{" "}
          <a
            href="https://unit-converters.vercel.app/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 hover:underline break-all"
          >
            https://unit-converters.vercel.app/
          </a>
        </li>

        <li>
          <strong className="text-black">You</strong> means the individual
          accessing or using the Service, or the company, or other legal entity
          on behalf of which such individual is accessing or using the Service,
          as applicable.
        </li>
      </ul>
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">
        Collecting and Using Your Personal Data
      </h2>
      <h3 className="font-bold text-xl sm:text-2xl mt-6">
        Types of Data Collected
      </h3>
      <h4 className="font-bold text-lg sm:text-xl mt-5">Personal Data</h4>
      <p className="mt-3 text-base sm:text-lg text-gray-500 leading-relaxed">
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <h4 className="font-bold text-lg sm:text-xl mt-5">Usage Data</h4>
      <p className="mt-3 text-base sm:text-lg text-gray-500 leading-relaxed">
        Usage Data is collected automatically when using the Service. Usage Data
        may include information such as Your Device's Internet Protocol address
        (e.g. IP address), browser type, browser version, the pages of our
        Service that You visit, the time and date of Your visit, the time spent
        on those pages, unique device identifiers and other diagnostic data.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device's unique ID,
        the IP address of Your mobile device, Your mobile operating system, the
        type of mobile Internet browser You use, unique device identifiers and
        other diagnostic data.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        We may also collect information that Your browser sends whenever You
        visit Our Service or when You access the Service by or through a mobile
        device.
      </p>
      {/* Cookies */}
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">
        Tracking Technologies and Cookies
      </h2>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies We
        use include beacons, tags, and scripts to collect and track information
        and to improve and analyze Our Service.
      </p>
      <h3 className="font-bold text-xl sm:text-2xl mt-6">
        Cookies or Browser Cookies
      </h3>
      <p className="mt-3 text-base sm:text-lg text-gray-500 leading-relaxed">
        A cookie is a small file placed on Your Device. You can instruct Your
        browser to refuse all Cookies or to indicate when a Cookie is being
        sent. However, if You do not accept Cookies, You may not be able to use
        some parts of our Service.
      </p>
      <h3 className="font-bold text-xl sm:text-2xl mt-6">Web Beacons</h3>
      <p className="mt-3 text-base sm:text-lg text-gray-500 leading-relaxed">
        Certain sections of our Service and our emails may contain small
        electronic files known as web beacons that permit the Company to count
        users who have visited those pages or opened an email and for other
        related website statistics.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
        remain on Your personal computer or mobile device when You go offline,
        while Session Cookies are deleted as soon as You close Your web browser.
      </p>
      <h3 className="font-bold text-xl sm:text-2xl mt-6">
        Types of Cookies We Use
      </h3>
      <ul className="mt-4 space-y-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        <li>
          <strong className="text-black">Necessary / Essential Cookies</strong>
          <br />
          <strong className="text-black">Type:</strong> Session Cookies
          <br />
          <strong className="text-black">Administered by:</strong> Us
          <br />
          <strong className="text-black">Purpose:</strong> These Cookies are
          essential to provide You with services available through the Website
          and to enable You to use some of its features.
        </li>

        <li>
          <strong className="text-black">
            Cookies Policy / Notice Acceptance Cookies
          </strong>
          <br />
          <strong className="text-black">Type:</strong> Persistent Cookies
          <br />
          <strong className="text-black">Administered by:</strong> Us
          <br />
          <strong className="text-black">Purpose:</strong> These Cookies
          identify if users have accepted the use of cookies on the Website.
        </li>

        <li>
          <strong className="text-black">Functionality Cookies</strong>
          <br />
          <strong className="text-black">Type:</strong> Persistent Cookies
          <br />
          <strong className="text-black">Administered by:</strong> Us
          <br />
          <strong className="text-black">Purpose:</strong> These Cookies allow
          us to remember choices You make when You use the Website, such as
          remembering your login details or language preference.
        </li>
      </ul>
      {/* Use of Personal Data */}
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">
        Use of Your Personal Data
      </h2>
      <p className="mt-3 text-base sm:text-lg text-gray-500">
        The Company may use Personal Data for the following purposes:
      </p>
      <ul className="mt-4 space-y-3 list-disc pl-6 text-base sm:text-lg text-gray-500 leading-relaxed">
        <li>
          To provide and maintain our Service, including to monitor the usage of
          our Service.
        </li>
        <li>
          To manage Your Account and Your registration as a user of the Service.
        </li>
        <li>
          For the performance of a contract and to provide products, items or
          services You have purchased.
        </li>
        <li>
          To contact You by email, telephone calls, SMS, or other equivalent
          forms of electronic communication.
        </li>
        <li>
          To provide You with news, special offers, and general information
          about goods, services and events.
        </li>
        <li>To manage Your requests and provide customer support.</li>
        <li>
          For business transfers such as mergers, acquisitions or restructuring.
        </li>
        <li>
          For other purposes such as data analysis, identifying usage trends and
          improving our Service.
        </li>
      </ul>
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">
        Sharing Your Personal Information
      </h2>
      <ul className="mt-4 space-y-3 list-disc pl-6 text-base sm:text-lg text-gray-500 leading-relaxed">
        <li>
          <strong className="text-black">With Service Providers:</strong> We may
          share Your personal information with Service Providers to monitor and
          analyze the use of our Service.
        </li>

        <li>
          <strong className="text-black">For business transfers:</strong> We may
          share or transfer Your personal information in connection with a
          merger, sale of Company assets, financing, or acquisition.
        </li>

        <li>
          <strong className="text-black">With Affiliates:</strong> We may share
          Your information with Our affiliates.
        </li>

        <li>
          <strong className="text-black">With business partners:</strong> We may
          share Your information with Our business partners to offer You certain
          products, services or promotions.
        </li>

        <li>
          <strong className="text-black">With other users:</strong> When You
          share personal information or interact in public areas, such
          information may be viewed by other users.
        </li>

        <li>
          <strong className="text-black">With Your consent:</strong> We may
          disclose Your personal information for any other purpose with Your
          consent.
        </li>
      </ul>
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">
        Retention of Your Personal Data
      </h2>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations, resolve disputes, and enforce our legal
        agreements and policies.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        The Company will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time, except
        when this data is used to strengthen the security or improve the
        functionality of Our Service.
      </p>
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">
        Transfer of Your Personal Data
      </h2>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        Your information, including Personal Data, is processed at the Company's
        operating offices and in any other places where the parties involved in
        the processing are located. This means that information may be
        transferred to computers located outside of Your country where data
        protection laws may differ.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        The Company will take all steps reasonably necessary to ensure that Your
        data is treated securely and in accordance with this Privacy Policy.
      </p>
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">
        Delete Your Personal Data
      </h2>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        You have the right to delete or request that We assist in deleting the
        Personal Data that We have collected about You.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        Our Service may give You the ability to delete certain information about
        You from within the Service.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        You may update, amend, or delete Your information at any time by signing
        in to Your Account, if you have one, and visiting the account settings
        section.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        Please note, however, that We may need to retain certain information
        when we have a legal obligation or lawful basis to do so.
      </p>
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">
        Disclosure of Your Personal Data
      </h2>
      <h3 className="font-bold text-xl sm:text-2xl mt-6">
        Business Transactions
      </h3>
      <p className="mt-3 text-base sm:text-lg text-gray-500 leading-relaxed">
        If the Company is involved in a merger, acquisition or asset sale, Your
        Personal Data may be transferred. We will provide notice before Your
        Personal Data is transferred.
      </p>
      <h3 className="font-bold text-xl sm:text-2xl mt-6">Law Enforcement</h3>
      <p className="mt-3 text-base sm:text-lg text-gray-500 leading-relaxed">
        Under certain circumstances, the Company may be required to disclose
        Your Personal Data if required to do so by law or in response to valid
        requests by public authorities.
      </p>
      <h3 className="font-bold text-xl sm:text-2xl mt-6">
        Other Legal Requirements
      </h3>
      <ul className="mt-4 space-y-3 list-disc pl-6 text-base sm:text-lg text-gray-500 leading-relaxed">
        <li>Comply with a legal obligation.</li>
        <li>Protect and defend the rights or property of the Company.</li>
        <li>Prevent or investigate possible wrongdoing.</li>
        <li>Protect the personal safety of Users or the public.</li>
        <li>Protect against legal liability.</li>
      </ul>
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">
        Security of Your Personal Data
      </h2>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        The security of Your Personal Data is important to Us, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While We strive to use commercially reasonable
        means to protect Your Personal Data, We cannot guarantee its absolute
        security.
      </p>
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">
        Children's Privacy
      </h2>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        If You are a parent or guardian and You are aware that Your child has
        provided Us with Personal Data, please contact Us. If We become aware
        that We have collected Personal Data from anyone under the age of 13
        without verification of parental consent, We take steps to remove that
        information from Our servers.
      </p>
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">
        Links to Other Websites
      </h2>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party's site. We strongly advise You to review the Privacy Policy
        of every site You visit.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </p>
      ={" "}
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">
        Changes to this Privacy Policy
      </h2>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        We will let You know via email and/or a prominent notice on Our Service,
        prior to the change becoming effective and update the "Last updated"
        date at the top of this Privacy Policy.
      </p>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </p>
      <h2 className="font-bold text-2xl sm:text-3xl mt-8">Contact Us</h2>
      <p className="mt-4 text-base sm:text-lg text-gray-500 leading-relaxed">
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <p className="mt-3 mb-10 text-base sm:text-lg text-gray-500">
        <strong className="text-black">By email:</strong>{" "}
        <a
          href="mailto:johndavidonline2@gmail.com"
          className="text-blue-600 hover:underline break-all"
        >
          johndavidonline2@gmail.com
        </a>
      </p>
    </div>
  );
};

export default page;
